FROM python:3.12-slim@sha256:86d3e4424d5e963e60594a3a6b4d597cc4d41f5152fe67a97a40dca9ea092475
WORKDIR /app
COPY requirements-proto.txt .
RUN python -m pip install --no-cache-dir --require-hashes -r requirements-proto.txt
COPY factory.proto .
RUN python -m grpc_tools.protoc --proto_path=. --python_out=. factory.proto
COPY publish_proto.py .
CMD ["python", "-u", "publish_proto.py"]
