[[remotes.reduct]]
name = "local"
url = "http://localhost:8333"
token_api = "***"
bucket = "my-bucket"
prefix = "ros_data/"


[[inputs.ros]]
name = "ros-local"
uri = "http://localhost:11311"
node_name = "reduct-bridge"


[[pipelines.ros1]]
name = "telemetry"
remote = "local"
input = "ros-local"

include_topics = ["/camera/*", "/lidar/points"]
exclude_topics = ["/camera/image_raw/compressed"]
static_labels = {source = "ros1", robot = "alpha"}
dynamic_labels = { x-position = { source = "/odom/pose/position/x", scope = "*" } }
