[[remotes.reduct]]
name = "local"
url = "http://localhost:8333"
token_api = "***"
bucket = "my-bucket"
prefix = "ros_data/"


[[inputs.ros]]
name = "ros-local"
uri = "http://localhost:11311"
node_name = "reduct-bridge"


[[inputs.shell]]
name = "shell-local"
repeat_interval = 10
command = "echo \"Payload, $(date --rfc-3339=ns)\""
entry_name = "shell_input"
content_type = "text/plain"
labels = [
    { regex = "Payload, (.*)", labels = { timestamp = "$1" } },
    { static = { source = "shell_command" } }
]


[[pipelines]]
name = "telemetry"
remote = "local"
input = "ros-local"


[[pipelines]]
name = "shell_pipeline"
remote = "local"
input = "shell-local"
labels = [
    { static = { source = "shell_pipeline", to = "*" } },
    { from = "shell_input", labels = [ "timestamp" ], to = "*" }
]
